apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amqonline-operators
  namespace: telemetry-hub
spec:
  targetNamespaces:
    - telemetry-hub
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-online
  namespace: telemetry-hub
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-online
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq-online.1.5.3
