apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: telemetry-hub.data
  labels:
    app: telemetry-hub
spec:
  address: events
  type: queue
  plan: standard-large-queue
---
apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: telemetry-hub.test
  labels:
    app: telemetry-hub
spec:
  address: ping
  type: multicast
  plan: standard-small-multicast
---
apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: telemetry-hub.update
  labels:
    app: telemetry-hub
spec:
  address: telemetry
  type: multicast
  plan: standard-large-multicast
